#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def _read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    keys = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def _to_float(v: object) -> float:
    if v is None:
        return float("nan")
    s = str(v).strip()
    if not s:
        return float("nan")
    try:
        return float(s)
    except ValueError:
        return float("nan")


def _to_int(v: object) -> int:
    x = _to_float(v)
    if x != x:
        return 0
    return int(x)


def _find_probe_bucket_row(rows: List[Dict[str, str]]) -> Optional[Dict[str, str]]:
    # Prefer "16+" (Gate1 pass), else fall back to the last row.
    for r in rows:
        if str(r.get("probe_bucket", "")) == "16+":
            return r
    return rows[-1] if rows else None


def _pick_stage_row(rows: List[Dict[str, str]], stage: str) -> Optional[Dict[str, str]]:
    for r in rows:
        if str(r.get("stage", "")) == stage:
            return r
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description="Summarize exp44 media sweep points into one compact trend table.")
    ap.add_argument("--sweep_points_csv", required=True, help="CSV generated by the sweep runner")
    ap.add_argument("--out_csv", required=True, help="Where to write the consolidated summary CSV")
    args = ap.parse_args()

    points = _read_csv(Path(args.sweep_points_csv).resolve())
    out_rows: List[Dict[str, object]] = []

    for p in points:
        run_dir = Path(str(p.get("run_dir", ""))).resolve()
        if not run_dir.exists():
            continue
        analysis_dir = run_dir / "analysis_readmissing_sample_cache_536870912"
        probe_path = analysis_dir / "sample_filter_probe_bucket_summary.csv"
        stage_path = analysis_dir / "sample_stage_distribution.csv"
        if not probe_path.exists() or not stage_path.exists():
            continue

        probe_rows = _read_csv(probe_path)
        stage_rows = _read_csv(stage_path)
        br = _find_probe_bucket_row(probe_rows)
        if br is None:
            continue

        # Key stages (p50 share).
        st_get = _pick_stage_row(stage_rows, "get_from_output_files")
        st_idx = _pick_stage_row(stage_rows, "index_lookup")
        st_fcpu = _pick_stage_row(stage_rows, "filter_maymatch_cpu")
        st_bio = _pick_stage_row(stage_rows, "block_read_io")

        out_rows.append(
            {
                "run_tag": p.get("run_tag", ""),
                "xp_latency_ns": _to_int(p.get("xp_latency_ns", 0)),
                "bypass_base_io": _to_int(p.get("bypass_base_io", 0)),
                "probe_bucket": br.get("probe_bucket", ""),
                "probe_median": _to_float(br.get("probe_median", "")),
                "samples": _to_int(br.get("samples", 0)),
                "latency_p50_us": _to_float(br.get("latency_p50_us", "")),
                "latency_p95_us": _to_float(br.get("latency_p95_us", "")),
                "filter_fetch_p50_us": _to_float(br.get("filter_fetch_p50_us", "")),
                "filter_fetch_p95_us": _to_float(br.get("filter_fetch_p95_us", "")),
                "filter_cpu_p50_us": _to_float(br.get("filter_cpu_p50_us", "")),
                "filter_cpu_p95_us": _to_float(br.get("filter_cpu_p95_us", "")),
                "filter_total_share_p50_pct": _to_float(br.get("filter_total_share_p50_pct", "")),
                "filter_fetch_share_p50_pct": _to_float(br.get("filter_fetch_share_p50_pct", "")),
                "filter_cpu_share_p50_pct": _to_float(br.get("filter_cpu_share_p50_pct", "")),
                "simfs_wait_actual_p50_us": _to_float(br.get("simfs_wait_actual_p50_us", "")),
                "simfs_injected_p50_us": _to_float(br.get("simfs_injected_p50_us", "")),
                "simfs_read_wall_p50_us": _to_float(br.get("simfs_read_wall_p50_us", "")),
                "base_over_injected_p50": _to_float(br.get("base_over_injected_p50", "")),
                "simfs_wait_actual_share_p50_pct": _to_float(br.get("simfs_wait_actual_share_p50_pct", "")),
                "simfs_injected_share_p50_pct": _to_float(br.get("simfs_injected_share_p50_pct", "")),
                "stage_get_from_output_files_p50_share_pct": _to_float(st_get.get("p50_share_pct", "")) if st_get else float("nan"),
                "stage_index_lookup_p50_share_pct": _to_float(st_idx.get("p50_share_pct", "")) if st_idx else float("nan"),
                "stage_filter_maymatch_cpu_p50_share_pct": _to_float(st_fcpu.get("p50_share_pct", "")) if st_fcpu else float("nan"),
                "stage_block_read_io_p50_share_pct": _to_float(st_bio.get("p50_share_pct", "")) if st_bio else float("nan"),
                "run_dir": str(run_dir),
            }
        )

    out_rows.sort(key=lambda r: (int(r["bypass_base_io"]), int(r["xp_latency_ns"])))
    _write_csv(Path(args.out_csv).resolve(), out_rows)
    print(f"[ok] wrote summary: {args.out_csv} (rows={len(out_rows)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

